# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf7e1b16069926a4e040ee33ae21d4b089f1ed569079331d5270d6de24caed5336b0130165d2bb97e7779024c95ac4080c0809d02181f6cc159a145fe122d9f7

test:
  secret_key_base: 9a572f3e82ae943d53358ff7f3238ea8fec260300f7230a601789456d3f1a39c4f0b089626f1cae7e2f0a577e665711af48089341f8f90e84198c23c5ef7fda1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
